### ISSUE TITLE
Cannot create context on OpenGL 2.1 GPU

### ISSUE THREAD

**Issue by LaineZ** [servo/surfman#198]
I tried run program that uses surfman for window creation - but it not works, crashes with this error:
```
thread 'main' panicked at 'TODO: ContextCreationFailed(BadMatch)', src/backend/gl/src/window/surfman.rs:152:27
```
glxinfo output: https://pastebin.com/XXmSBMCp

**Comment by hurufu** [comment]
Same here, probably it will never be supported:
```
Failed to create WR surfman: ContextCreationFailed(BadMatch) (thread main, at ports/winit/headed_window.rs:158)
```
